name: release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.target_commitish }}

      - name: Generate changelog for this release
        id: changelog
        uses: janheinrichmerker/action-github-changelog-generator@v2.4
        with:
          token: ${{ secrets.CHANGELOG_TOKEN }}

      - name: Create PR
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: changelog-update-${{ github.event.release.tag_name }}
          title: "docs: update CHANGELOG for ${{ github.event.release.tag_name }}"
          body: "Automated changelog update."
          base: main

      - name: Auto-merge PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}
          merge-method: squash

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Package
        run: yarn run package

      #- name: Download ScanCode Toolkit
      #  run: |
      #    curl -L -o scancode-toolkit.tar.gz https://github.com/aboutcode-org/scancode-toolkit/releases/download/v32.3.0/scancode-toolkit-v32.3.0_py3.12-linux.tar.gz
      #    mkdir -p scancode-toolkit
      #    tar -xzf scancode-toolkit.tar.gz -C scancode-toolkit --strip-components=1
  
      #- name: Set up Python 3.12
      #  uses: actions/setup-python@v5
      #  with:
      #    python-version: 3.12
  
      #- name: Run ScanCode
      #  run: |
      #    cd scancode-toolkit
      #    ./scancode --json-pp ../scancode-result.json ../

      - name: Prepare release artifacts
        run: |
          mkdir -p release
          cp CHANGELOG.md release/
          cp lichtblick.asam-osi-converter-*.foxe release/

      - name: Upload deliverables
        uses: svenstaro/upload-release-action@v2
        with:
          file: release/*
          file_glob: true
          tag: ${{ github.event.release.tag_name }}
          overwrite: true
