name: release

on:
  push:
    tags: ["v[0-9].[0-9]+.[0-9]+"]

jobs:
  changelog:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0
        
      - name: Switch to main branch
        run: |
          git checkout main
          git pull origin main

      - name: Generate changelog for this release
        uses: janheinrichmerker/action-github-changelog-generator@v2.4

      - name: Commit updated CHANGELOG.md
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "docs: update CHANGELOG for ${{ github.ref_name }}"
          git push origin main

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Package
        run: yarn run package

      #- name: Download ScanCode Toolkit
      #  run: |
      #    curl -L -o scancode-toolkit.tar.gz https://github.com/aboutcode-org/scancode-toolkit/releases/download/v32.3.0/scancode-toolkit-v32.3.0_py3.12-linux.tar.gz
      #    mkdir -p scancode-toolkit
      #    tar -xzf scancode-toolkit.tar.gz -C scancode-toolkit --strip-components=1
  
      #- name: Set up Python 3.12
      #  uses: actions/setup-python@v5
      #  with:
      #    python-version: 3.12
  
      #- name: Run ScanCode
      #  run: |
      #    cd scancode-toolkit
      #    ./scancode --json-pp ../scancode-result.json ../

      - name: Extract version
        id: extract_version
        run: |
          version=$(node -p "require('./package.json').version")
          echo "version=$version" >> $GITHUB_ENV

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: "plu5/automatic-releases-with-sha-action@main"
        with:
          repo_token: "${{ secrets.PAT_TOKEN }}"
          prerelease: false
          title: ASAM OSI Converter ${{ github.ref_name }}
          files: |
            CHANGELOG.md
            scancode-result.json
            lichtblick.asam-osi-converter-${{ env.version }}.foxe
